version: "3.8"
networks:
  app_network:
    driver: bridge

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "4571:4571"
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - SERVICES=apigateway,lambda,iam,logs
      - GATEWAY_LISTEN=4566
      - LOCALSTACK_PERSISTENCE=${LOCALSTACK_PERSISTENCE:-1}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app_network

  mockserver:
    image: mockserver/mockserver:mockserver-5.15.0
    container_name: mockserver
    ports:
      - "1080:1080"
    environment:
      - MOCKSERVER_WATCH_INITIALIZATION_JSON=true
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/**/*.json
      - LOG_LEVEL_DEBUG=true
    volumes:
      - type: bind
        source: ./mockserver
        target: /config
    networks:
      - app_network
