name: Build & Release

on:
  push:
    branches: [master, alpha, beta, rc]
  pull_request:
    branches: [master]
    types: [opened, synchronize, closed]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - name: Run lint ğŸ”
        run: yarn lint

  test-lambda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - name: Run test ğŸ”
        run: yarn test:lambda

  test-domain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - name: Run test ğŸ”
        run: yarn test:domain

  test-controllers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - name: Run test ğŸ”
        run: yarn test:controllers

  test-infra:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - name: Run test ğŸ”
        run: yarn test:infra

  test-commands:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - name: Run test ğŸ”
        run: yarn test:commands

  test-www:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - name: Run test ğŸ”
        run: yarn test:www

  test-e2e:
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"
      - name: Install dependencies ğŸš€
        run: yarn install --immutable --network-timeout 500000
      - uses: hashicorp/setup-terraform@v3
      - name: Start localstack ğŸš§
        run: yarn run start:docker -d
      - name: Build & Deploy lambda ğŸš§
        run: yarn deploy:lambda
      - name: Run test ğŸ”
        run: yarn test:e2e
      - name: Stop containers
        if: always()
        run: yarn stop:docker
